### ISSUE TITLE
Problem viewing pages in admin section when dynamiccache turned on 

### ISSUE THREAD

**Issue by colinburns** [tractorcow/silverstripe-dynamiccache#11]
Hi Guys,

I'm having some problems that I thought someone here might be able to shed some light on. When I enable dynamiccache via the config.yml file - which I have copied over from dynamiccache.yml file I am able to get into the CMS section but unable to do anything in there. For example if I click on a page in the site tree then I get the "loading" image come up but the page doesn't change at all. If I click into security or any other section the same thing happens.

I assume I just have something configured incorrectly in the cache. I can't see any error messages coming up or in my log file so I don't really know where to start looking... 

Here is my config.yml file.

Sorry if I am posting this in the wrong place.

Cheers,
Colin

```
DynamicCache:
# Global override. Turn to false to turn caching off.
  enabled: true
# If a header should be used to opt in to caching, set the regular expression
# here which will match the specified header.
  optInHeader: null
# If a header should be used to explicitly disable caching for a cache, set the
# regular expression here which will be used to match the specified header
  optOutHeader: '/^X\-DynamicCache\-OptOut/'
# Header to use by the module attempting to opt out
  optOutHeaderString: 'X-DynamicCache-OptOut: true'
# Header prefix to use for reporting cache results
  responseHeader: 'X-DynamicCache'
# If caching should be limited only to specified urls set the regular expression
# here which will be used to match those urls
  optInURL: null
# If caching should be disabled for specified urls set the regular expression here
# which will be used to match those urls
  optOutURL: '/(^\/admin)|(^\/dev($|\/))|(\/[A-Z])/'
# Determine if caching should be separated for different hostnames. Important if
# running off a system that serves different content for different hostname, but
# still uses the same backend, such as the subsites module
  segmentHostname: true
# Determine if caching should be enabled during ajax
  enableAjax: false
# Duration of the page cache, in seconds
  cacheDuration: 3600
# Determines which headers should also be cached. X-Include-CSS and other relevant
# headers can be essential in instructing the front end to include specific
# resource files
  cacheHeaders: '/^X\-/i'
# If you wish to override the cache configuration, then change this to another
# backend, and initialise a new SS_Cache backend in your _config file
  cacheBackend: 'DynamicCache'
```
