### ISSUE TITLE
Config File has no "Name"

### ISSUE THREAD

**Issue by RoyalPulp** [tractorcow/silverstripe-dynamiccache#21]
Hello!
When configuring other modules with my own *.yml file, I can tell Silverstripe to process my config file after the original config file of the module. 
But to do that, each configuration file needs a name definition.

So the first 3 lines inside the dynamiccache.yml file shoud be something like this:

``` yml

---
Name: dynamiccacheconfig

---
```

Example (Fluent Module):

/fluent/_config/fluent.yml

``` yml

---
Name: fluentconfig

---
Fluent:
  # Don't forget to set i18n->default_locale too!
  default_locale: en_NZ
  locales: []
#(...)
```

/mysite/_config/fluent.yml

``` yml

---
Name: myfluentconfig
After: '#fluentconfig'

---
Fluent:
  detect_locale: false
  remember_locale: false
  default_locale: de_DE
  locales:
    - de_DE
    - nl_NL
    - en_US
#(...)
```

Regards,
Hendrik
